### PR TITLE
Add loop_limit, loop_idx keyword parameters to callbacks

### PR DESCRIPTION
**Pull request by Baughn**
For use with errorcontrol=True, this allows users to e.g. display a
progress bar.

---

This change is [Reviewable](https://reviewable.io/reviews/andim/noisyopt/3)

### CODE REVIEW

**Comment by Baughn** [comment]
Oh yay, test failures. ...

I'm going on vacation Thursday, and will be busy until then, so this PR may languish for a while until I can get to it, but I'll find a solution eventually. Meanwhile, is this an architecture you'd approve of? Or would you prefer special-purpose callbacks or something?

**Comment by andim** [comment]
I'm not sure I understand exactly what you are proposing. Could you elaborate? For the pattern-search based algorithm there is no predetermined number of overall evaluations so I don't see how to return this to the callback function. If you want to have an iteration number count for your callback, just count inside this function (e.g. as described here http://stackoverflow.com/questions/21716940/is-there-a-way-to-track-the-number-of-times-a-function-is-called).

In general the aim is to be compatible with scipy optimize routines which simply call the callback function with the current parameter value. If there is no very strong rationale for breaking this compatibility I would not want to do so.

**Comment by Baughn** [comment]
The idea is to provide progress bars, basically. So I'd need the number of iterations of any given parameter set, as well as the intended maximum.

Then there's a chance the optimizer will decide that wasn't enough, but most of the time it doesn't, and users will at least be able to tell that something is happening.

If you don't want to add a keyword parameter, then how about a secondary callback?

**Comment by andim** [comment]
Have you had a look at the status updates provided by `disp=True`? If the user just wants to know what is going on that should be enough. If one really wants to have a progress bar I think it would be preferable to have all that logic externally, just based on the simple callback provided by the routine.

**Comment by Baughn** [comment]
I've looked at it. It contains the sort of implementation detail that end-users would have no idea what to do with; it helped a lot when coding, but printing it from inside noisyopt is not flexible enough.

Well, then here's an idea. An info_callback, which includes both the data which would be printed by disp and the iteration-counter I need. That would even let me provide a global progress bar to go with the per-configuration one.

**Comment by andim** [comment]
Have you followed up in any way on this? Otherwise I would be inclined to close the PR. As I've outlined above I believe it is preferable to implement the counting logic within the callback function.

**Comment by Baughn** [comment]
Partly. I didn't find a good excuse yet to work on this in a hobby project, which is *probably* what I'd need to do a really good job, but I *have* found the time recently to work on it at work.

That being said, I'll close the PR for now and reopen once I have something you may be happy with, so it doesn't clutter up the list. Hope to talk to you later.

**Pull request closed without merging**
